[package]
name = "ha-gpio-mqtt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rppal = "0.18.0"
rumqttc = "0.24.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
